graph TD
    node_0["醫生協會"]
    node_1["市中心"]
    node_2["科學之路"]
    node_3["惠斯同橋"]
    node_4["往綠血小鬼之森的小徑"]
    node_5["綠血小鬼之森"]
    node_6["山腳下"]
    node_7["凍原"]
    node_8["凍原山頂"]
    node_9["紙路"]
    node_10["文明之路"]
    node_11["郵局"]
    node_12["風采裝備倉庫"]
    node_13["和平大道"]
    node_14["濟慈醫院"]
    node_15["協會走廊"]
    node_16["外科協會"]
    node_17["外科手術室"]
    node_18["協會IDLE處"]
    node_19["安老所"]
    node_20["殯儀館"]
    node_21["臨時醫療所"]
    node_22["醉翁亭"]
    node_23["聊天室(C)"]
    node_24["聊天室(D)"]
    node_25["咖啡  地  窖"]
    node_26["咖啡　雜物倉"]
    node_27["咖啡　防具庫"]
    node_28["咖啡　丹藥房"]
    node_29["咖啡　兵器庫"]
    node_30["〃85〃主吧檯"]
    node_31["〃85〃學徒室"]
    node_32["〃85〃留言板"]
    node_33["〃85〃候客廳"]
    node_34["〃85〃佈告欄"]
    node_35["〃85〃店門口"]
    node_36["奴隸拍賣場"]
    node_37["奴隸估價所"]
    node_38["奴隸訓練所"]
    node_39["你從戰鬥中祈求天神的傳送. 你損失了 100 點的經驗值."]
    node_40["街道"]
    node_41["大英王城入口"]
    node_42["王城噴泉"]
    node_43["山腹隧道"]
    node_44["十字路口"]
    node_45["托育中心"]
    node_46["圖書館前廣場"]
    node_47["梅塔-利卡那-國道"]
    node_48["賈府正門"]
    node_49["皇陵深處"]
    node_50["訓練場"]
    node_51["皇宮"]
    node_52["戰鬥模擬室[4]"]
    node_53["魔谷中"]
    node_54["錦緻綢緞店"]
    node_55["明晴街"]
    node_56["修羅內城道路"]
    node_57["你蹺蹺的潛入禁區中....."]
    node_58["珠江"]
    node_59["巨石道上"]
    node_60["草食恐龍區"]
    node_61["安化大街"]
    node_62["牆邊路"]
    node_63["刀鋸地獄"]
    node_64["守衛處"]
    node_65["山腳下的市集"]
    node_66["龍穴中"]
    node_67["古堡內"]
    node_68["魔法學徒的營房"]
    node_69["服飾部"]
    node_70["天空之城"]
    node_71["通化門"]
    node_72["泥沼地帶"]
    node_73["水松森林"]
    node_74["北方公路"]
    node_75["大廳"]
    node_76["蘋果屋"]
    node_77["棋盤 ( 五 , 二 )"]
    node_78["海底餐廳 1"]
    node_79["雲端上"]
    node_80["小屋子"]
    node_81["深山中"]
    node_82["武家屋敷-城牆走道"]
    node_83["蒙古軍營"]
    node_84["[梅塔-利卡那森林]"]
    node_85["大洞窟"]
    node_86["走廊"]
    node_87["[林奇的駐紮地]"]
    node_88["進出口"]
    node_89["戰鬥模擬室[9]"]
    node_90["通道"]
    node_91["廂房走廊"]
    node_92["金龍殿的上方"]
    node_93["碼頭"]
    node_94["仙音階"]
    node_95["武當山頂"]
    node_96["接天門"]
    node_97["殿前廣場"]
    node_98["石香爐"]
    node_99["殿前迴廊"]
    node_100["殿旁走道"]
    node_101["俞岱岩臥室"]
    node_102["張松溪臥室"]
    node_103["防具庫房"]
    node_104["兵器庫房"]
    node_105["俞蓮舟臥室"]
    node_106["宋遠橋臥室"]
    node_107["宋青書臥室"]
    node_108["張三豐禪房"]
    node_109["便利商店"]
    node_110["大學校門口"]
    node_111["[ 四度空間 勇者之訓練學校入口]"]
    node_112["勒曼醫院"]
    node_113["階梯頂端"]
    node_114["荒地"]
    node_115["太平洋"]
    node_116["大樹枝上"]
    node_117["山谷深處"]
    node_118["秘密通道"]
    node_119["玩偶區"]
    node_120["小蛇徑"]
    node_121["科學展覽會場"]
    node_122["科幻電影院入口"]
    node_123["地藏廟"]
    node_124["科幻電影院Ａ廳"]
    node_125["科幻電影院Ｂ廳"]
    node_126["旅店前"]
    node_127["森林人旅店"]
    node_128["吟遊詩人的座位"]
    node_129["安靜的客房區"]
    node_130["密林中"]
    node_131["岔路"]
    node_132["黑暗的小路"]
    node_133["陰暗的森林"]
    node_134["林中深處"]
    node_135["山腹中的隧道"]
    node_136["小石室"]
    node_137["綠血小鬼的巢穴"]
    node_138["屠殺現場"]
    node_139["森林深處"]
    node_140["小路的盡頭"]
    node_141["林間小徑"]
    node_142["COOL 往南邊飛走了."]
    node_143["COOL 往西邊飛走了."]
    node_144["COOL 往北邊飛走了."]
    node_145["COOL 往東邊飛走了."]
    node_146["COOL 往上邊飛走了."]
    node_147["魔の大殿"]
    node_148["王座遺址"]
    node_149["皇城後廳"]
    node_150["瀑布前"]
    node_151["長廊"]
    node_152["遺跡大門"]
    node_153["黑色的大橋上"]
    node_154["山坡的頂端"]
    node_155["山坡上"]
    node_156["〃85〃調飲間"]
    node_157["〃85〃佛  堂"]
    node_158["〃85〃茶水間"]
    node_159["〃85〃交誼廳"]
    node_160["〃HS〃停車場"]
    node_161["〃HS〃御書房"]
    node_162["〃HS〃天文台"]
    node_163["〃85〃海盜船"]
    node_164["〃85〃水族箱"]
    node_165["〃85〃竹葉林"]
    node_166["〃85〃觀星坪"]
    node_167["〃85〃惡人谷"]
    node_168["〃85〃小花圃"]
    node_169["〃85〃水果田"]
    node_170["請輸入你在本遊戲中所使用的名字 ID NAME?"]
    node_171["[出口: 東 西 上]"]
    node_172["[出口: 北 東 南 西]"]
    node_173["[出口: 北 東 南 西 上]"]
    node_174["[出口: 北 東 南 西 下]"]
    node_175["[出口: 北 南]"]
    node_176["[出口: 東]"]
    node_177["[出口: 東 西]"]
    node_178["[出口: 北 南 西]"]
    node_179["[出口: 東 南]"]
    node_180["[出口: 北 西]"]
    node_181["[出口: 南]"]
    node_182["[出口: 北 東 南]"]
    node_183["[出口: 東 南 西]"]
    node_184["[出口: 東 上]"]
    node_185["[出口: 西 上]"]
    node_186["[出口: 北]"]
    node_187["[出口: 北 東]"]
    node_188["[出口: 北 東 西]"]
    node_189["[出口: 南 西]"]
    node_190["[出口: 下]"]
    node_0 -- "move" --> node_1
    node_1 -- "move" --> node_2
    node_2 -- "move" --> node_3
    node_3 -- "move" --> node_4
    node_4 -- "move" --> node_5
    node_5 -- "move" --> node_6
    node_6 -- "move" --> node_7
    node_7 -- "move" --> node_8
    node_8 -- "move" --> node_9
    node_9 -- "move" --> node_1
    node_1 -- "move" --> node_10
    node_10 -- "move" --> node_11
    node_11 -- "move" --> node_12
    node_12 -- "move" --> node_0
    node_0 -- "move" --> node_13
    node_13 -- "move" --> node_14
    node_14 -- "move" --> node_15
    node_15 -- "move" --> node_16
    node_16 -- "move" --> node_15
    node_15 -- "move" --> node_17
    node_17 -- "move" --> node_15
    node_15 -- "move" --> node_18
    node_18 -- "move" --> node_15
    node_15 -- "move" --> node_14
    node_14 -- "move" --> node_19
    node_19 -- "move" --> node_14
    node_14 -- "move" --> node_20
    node_20 -- "move" --> node_14
    node_14 -- "move" --> node_21
    node_21 -- "move" --> node_14
    node_14 -- "move" --> node_13
    node_13 -- "move" --> node_0
    node_1 -- "move" --> node_13
    node_13 -- "move" --> node_22
    node_22 -- "move" --> node_13
    node_13 -- "move" --> node_1
    node_2 -- "move" --> node_23
    node_23 -- "move" --> node_2
    node_2 -- "move" --> node_24
    node_24 -- "move" --> node_2
    node_23 -- "move" --> node_0
    node_0 -- "move" --> node_25
    node_25 -- "move" --> node_26
    node_26 -- "move" --> node_25
    node_25 -- "move" --> node_27
    node_27 -- "move" --> node_25
    node_25 -- "move" --> node_28
    node_28 -- "move" --> node_25
    node_25 -- "move" --> node_29
    node_29 -- "move" --> node_25
    node_25 -- "move" --> node_30
    node_30 -- "move" --> node_31
    node_31 -- "move" --> node_30
    node_30 -- "move" --> node_32
    node_32 -- "move" --> node_30
    node_30 -- "move" --> node_33
    node_33 -- "move" --> node_34
    node_34 -- "move" --> node_35
    node_35 -- "move" --> node_34
    node_34 -- "move" --> node_33
    node_33 -- "move" --> node_30
    node_30 -- "move" --> node_1
    node_14 -- "move" --> node_1
    node_12 -- "move" --> node_11
    node_11 -- "move" --> node_36
    node_36 -- "move" --> node_37
    node_37 -- "move" --> node_38
    node_38 -- "move" --> node_39
    node_39 -- "move" --> node_40
    node_40 -- "move" --> node_41
    node_41 -- "move" --> node_42
    node_42 -- "move" --> node_43
    node_43 -- "move" --> node_44
    node_44 -- "move" --> node_45
    node_45 -- "move" --> node_46
    node_46 -- "move" --> node_47
    node_47 -- "move" --> node_48
    node_48 -- "move" --> node_49
    node_49 -- "move" --> node_50
    node_50 -- "move" --> node_51
    node_51 -- "move" --> node_52
    node_52 -- "move" --> node_53
    node_53 -- "move" --> node_54
    node_54 -- "move" --> node_55
    node_55 -- "move" --> node_56
    node_56 -- "move" --> node_57
    node_57 -- "move" --> node_58
    node_58 -- "move" --> node_59
    node_59 -- "move" --> node_60
    node_60 -- "move" --> node_61
    node_61 -- "move" --> node_62
    node_62 -- "move" --> node_63
    node_63 -- "move" --> node_64
    node_64 -- "move" --> node_39
    node_39 -- "move" --> node_65
    node_65 -- "move" --> node_66
    node_66 -- "move" --> node_67
    node_67 -- "move" --> node_68
    node_68 -- "move" --> node_69
    node_69 -- "move" --> node_64
    node_64 -- "move" --> node_1
    node_1 -- "move" --> node_70
    node_70 -- "move" --> node_71
    node_71 -- "move" --> node_72
    node_72 -- "move" --> node_73
    node_73 -- "move" --> node_74
    node_74 -- "move" --> node_75
    node_75 -- "move" --> node_76
    node_76 -- "move" --> node_77
    node_77 -- "move" --> node_78
    node_78 -- "move" --> node_79
    node_79 -- "move" --> node_80
    node_80 -- "move" --> node_81
    node_81 -- "move" --> node_82
    node_82 -- "move" --> node_83
    node_83 -- "move" --> node_84
    node_84 -- "move" --> node_85
    node_85 -- "move" --> node_86
    node_86 -- "move" --> node_87
    node_87 -- "move" --> node_88
    node_88 -- "move" --> node_89
    node_89 -- "move" --> node_90
    node_90 -- "move" --> node_91
    node_91 -- "move" --> node_92
    node_92 -- "move" --> node_93
    node_93 -- "move" --> node_94
    node_94 -- "move" --> node_95
    node_95 -- "move" --> node_96
    node_96 -- "move" --> node_97
    node_97 -- "move" --> node_96
    node_96 -- "move" --> node_95
    node_95 -- "move" --> node_94
    node_97 -- "move" --> node_98
    node_98 -- "move" --> node_99
    node_99 -- "move" --> node_100
    node_100 -- "move" --> node_99
    node_99 -- "move" --> node_98
    node_100 -- "move" --> node_101
    node_101 -- "move" --> node_100
    node_100 -- "move" --> node_102
    node_102 -- "move" --> node_100
    node_100 -- "move" --> node_103
    node_103 -- "move" --> node_100
    node_100 -- "move" --> node_104
    node_104 -- "move" --> node_100
    node_100 -- "move" --> node_105
    node_105 -- "move" --> node_100
    node_100 -- "move" --> node_106
    node_106 -- "move" --> node_100
    node_100 -- "move" --> node_107
    node_107 -- "move" --> node_100
    node_100 -- "move" --> node_108
    node_108 -- "move" --> node_100
    node_108 -- "move" --> node_21
    node_13 -- "move" --> node_109
    node_109 -- "move" --> node_1
    node_2 -- "move" --> node_110
    node_110 -- "move" --> node_111
    node_111 -- "move" --> node_112
    node_112 -- "move" --> node_1
    node_11 -- "move" --> node_113
    node_113 -- "move" --> node_114
    node_114 -- "move" --> node_115
    node_115 -- "move" --> node_116
    node_116 -- "move" --> node_117
    node_117 -- "move" --> node_118
    node_118 -- "move" --> node_119
    node_119 -- "move" --> node_120
    node_120 -- "move" --> node_1
    node_2 -- "move" --> node_121
    node_121 -- "move" --> node_2
    node_110 -- "move" --> node_2
    node_2 -- "move" --> node_122
    node_122 -- "move" --> node_2
    node_2 -- "move" --> node_123
    node_123 -- "move" --> node_2
    node_122 -- "move" --> node_124
    node_124 -- "move" --> node_125
    node_125 -- "move" --> node_124
    node_124 -- "move" --> node_122
    node_4 -- "move" --> node_126
    node_126 -- "move" --> node_127
    node_127 -- "move" --> node_128
    node_128 -- "move" --> node_127
    node_127 -- "move" --> node_129
    node_129 -- "move" --> node_127
    node_127 -- "move" --> node_126
    node_126 -- "move" --> node_4
    node_6 -- "move" --> node_5
    node_5 -- "move" --> node_130
    node_130 -- "move" --> node_131
    node_131 -- "move" --> node_72
    node_72 -- "move" --> node_132
    node_132 -- "move" --> node_130
    node_130 -- "move" --> node_133
    node_133 -- "move" --> node_134
    node_134 -- "move" --> node_135
    node_135 -- "move" --> node_136
    node_136 -- "move" --> node_135
    node_135 -- "move" --> node_137
    node_137 -- "move" --> node_135
    node_135 -- "move" --> node_134
    node_134 -- "move" --> node_133
    node_133 -- "move" --> node_138
    node_138 -- "move" --> node_139
    node_139 -- "move" --> node_140
    node_140 -- "move" --> node_141
    node_141 -- "move" --> node_1
    node_1 -- "move" --> node_142
    node_142 -- "move" --> node_143
    node_143 -- "move" --> node_144
    node_144 -- "move" --> node_145
    node_145 -- "move" --> node_144
    node_144 -- "move" --> node_146
    node_146 -- "move" --> node_144
    node_145 -- "move" --> node_147
    node_147 -- "move" --> node_148
    node_148 -- "move" --> node_149
    node_149 -- "move" --> node_150
    node_150 -- "move" --> node_149
    node_149 -- "move" --> node_148
    node_148 -- "move" --> node_147
    node_147 -- "move" --> node_151
    node_151 -- "move" --> node_152
    node_152 -- "move" --> node_153
    node_153 -- "move" --> node_154
    node_154 -- "move" --> node_155
    node_155 -- "move" --> node_65
    node_65 -- "move" --> node_141
    node_141 -- "move" --> node_140
    node_140 -- "move" --> node_139
    node_139 -- "move" --> node_35
    node_30 -- "move" --> node_156
    node_156 -- "move" --> node_30
    node_33 -- "move" --> node_157
    node_157 -- "move" --> node_158
    node_158 -- "move" --> node_157
    node_157 -- "move" --> node_159
    node_159 -- "move" --> node_160
    node_160 -- "move" --> node_161
    node_161 -- "move" --> node_162
    node_162 -- "move" --> node_161
    node_161 -- "move" --> node_160
    node_160 -- "move" --> node_159
    node_159 -- "move" --> node_157
    node_157 -- "move" --> node_163
    node_163 -- "move" --> node_164
    node_164 -- "move" --> node_165
    node_165 -- "move" --> node_166
    node_166 -- "move" --> node_165
    node_165 -- "move" --> node_164
    node_164 -- "move" --> node_163
    node_163 -- "move" --> node_167
    node_167 -- "move" --> node_168
    node_168 -- "move" --> node_169
    node_169 -- "move" --> node_168
    node_168 -- "move" --> node_167
    node_167 -- "move" --> node_163
    node_163 -- "move" --> node_157
    node_162 -- "move" --> node_35
    node_30 -- "move" --> node_25
    node_25 -- "move" --> node_1
    node_22 -- "move" --> node_35
    node_35 -- "move" --> node_1
    node_142 -- "move" --> node_35
    node_35 -- "move" --> node_170
    node_170 -- "move" --> node_171
    node_171 -- "move" --> node_172
    node_172 -- "move" --> node_173
    node_173 -- "move" --> node_172
    node_172 -- "move" --> node_174
    node_174 -- "move" --> node_175
    node_175 -- "move" --> node_172
    node_172 -- "move" --> node_176
    node_176 -- "move" --> node_172
    node_172 -- "move" --> node_177
    node_177 -- "move" --> node_172
    node_177 -- "move" --> node_178
    node_178 -- "move" --> node_175
    node_175 -- "move" --> node_179
    node_179 -- "move" --> node_177
    node_177 -- "move" --> node_180
    node_180 -- "move" --> node_181
    node_181 -- "move" --> node_172
    node_175 -- "move" --> node_182
    node_182 -- "move" --> node_183
    node_183 -- "move" --> node_182
    node_182 -- "move" --> node_175
    node_175 -- "move" --> node_174
    node_174 -- "move" --> node_184
    node_184 -- "move" --> node_172
    node_172 -- "move" --> node_183
    node_183 -- "move" --> node_172
    node_172 -- "move" --> node_185
    node_185 -- "move" --> node_174
    node_174 -- "move" --> node_186
    node_186 -- "move" --> node_174
    node_174 -- "move" --> node_172
    node_172 -- "move" --> node_175
    node_175 -- "move" --> node_178
    node_178 -- "move" --> node_183
    node_183 -- "move" --> node_178
    node_183 -- "move" --> node_176
    node_176 -- "move" --> node_187
    node_187 -- "move" --> node_188
    node_188 -- "move" --> node_179
    node_179 -- "move" --> node_188
    node_179 -- "move" --> node_189
    node_189 -- "move" --> node_180
    node_180 -- "move" --> node_189
    node_180 -- "move" --> node_188
    node_188 -- "move" --> node_180
    node_188 -- "move" --> node_171
    node_183 -- "move" --> node_184
    node_184 -- "move" --> node_190
    node_190 -- "move" --> node_172
    node_173 -- "move" --> node_1
