print("--- Beginning Log Folding Test (Check Log File) ---")
print("Line A")
print("Line B (Repeat 3 times)")
print("Line B (Repeat 3 times)")
print("Line B (Repeat 3 times)")
print("Line C")
print("Line D (Repeat 2 times)")
print("Line D (Repeat 2 times)")
print("--- End Log Folding Test ---")
print("Please check the log file in logs/ directory to verify folding.")
